### ISSUE TITLE
ERROR in ./~/css-loader!./~/sass-loader!./src/assets/stylesheets/base.scss

### ISSUE THREAD

**Issue by blairanderson** [alanbsmith/react-node-example#1]
fresh install and start throws error 

``` bash
ERROR in ./~/css-loader!./~/sass-loader!./src/assets/stylesheets/base.scss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (dev/react-wizard/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (dev/react-wizard/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (dev/react-wizard/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (dev/react-wizard/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/assets/stylesheets/base.scss 4:14-127 13:2-17:4 14:20-133
```

**Comment by blairanderson** [comment]
removing style import from App.js builds without an error

**Comment by alanbsmith** [comment]
interesting. I'll take a look @blairanderson. This hasn't been an issue for me. Thanks for letting me know!

**Comment by alanbsmith** [comment]
upgrading to Node v.5 resolved this.
